### ISSUE TITLE
现在的xcode9环境完全没法用了。怎么不维护了？

### ISSUE THREAD

**Issue by wangier** [NetEaseGame/iOS-private-api-checker#16]
现在的xcode9环境完全没法用了。怎么不维护了？

**Comment by vbonluk** [comment]
+1

**Comment by columbusLGEN** [comment]
可以用，我解决了，大家请参考http://blog.yahui.wang/2017/05/31/iOS-private-api-checker-tools/

**Comment by LanCat** [comment]
eworks/SceneKit.framework) doesn't contain an executable.
Traceback (most recent call last):
  File "build_api_db.py", line 157, in <module>
    rebuild_sdk_private_api(sdk_version, False)
  File "build_api_db.py", line 135, in rebuild_sdk_private_api
    print rebuild_dump_framework_api(sdk_version['sdk'], sdk_version['framework'])
  File "build_api_db.py", line 55, in rebuild_dump_framework_api
    framework_dump_header_apis = api_utils.framework_dump_apis(sdk, framework_folder)
  File "/Users/caoshuai/Downloads/iOS-private-api-checker-master/api/api_utils.py", line 25, in framework_dump_apis
    all_headers = _get_headers_from_path(framework_header_folder)
  File "/Users/caoshuai/Downloads/iOS-private-api-checker-master/api/api_utils.py", line 127, in _get_headers_from_path
    frameworks = os.listdir(framework_folder)
OSError: [Errno 2] No such file or directory: '/Users/caoshuai/Downloads/iOS-private-api-checker-master/tmp/pub-headers'
报错啊 有谁知道怎么解决

**Comment by zhangkn** [comment]
mkdir -p /Users/caoshuai/Downloads/iOS-private-api-checker-master/tmp/pub-headers
