### ISSUE TITLE
运行db/dsidx_dbs.py报错

### ISSUE THREAD

**Issue by dengly** [NetEaseGame/iOS-private-api-checker#2]
dengliaoyandeMacBook-Pro:iOS-private-api-checker-master dengliaoyan$ python run_web.py
Traceback (most recent call last):
  File "run_web.py", line 9, in <module>
    from app import app
  File "/Users/dengliaoyan/Downloads/iOS-private-api-checker-master/app/__init__.py", line 7, in <module>
    from flask import Flask
ImportError: No module named flask

**Comment by dengly** [comment]
dengliaoyan$ python db/dsidx_dbs.py
Traceback (most recent call last):
  File "db/dsidx_dbs.py", line 7, in <module>
    from db.sqlite_utils import SqliteHandler
ImportError: No module named db.sqlite_utils
